[versions]
core-ktx-version = "1.12.0"
appcompat-version = "1.6.1"
material-version = "1.11.0"
constraintlayout-version = "1.11.0"
agp-version = "8.2.0"
kotlin-version = "1.9.21"

[libraries]
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx-version" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat-version" }
material = { group = "com.google.android.material", name = "material", version.ref = "material-version" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout-version" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp-version" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-version" }